# Introduction

##### Follow these steps as a guide and you will be able to access data on county health. You will be pulling out and filtering data until you only have that data that you need.

# Set Up

##### 1. Download Anaconda Navigator.
##### 2. Make a folder and put the CountyHealthData_2014-2015 (1).csv file in it. 
##### 3. Launch Jupyter Lab through Anaconda Navigator (you will find the folder that you just created in here). 
##### 4. After launching Jupyter Lab and finding your folder open a new tab.

# First Steps

##### Pandas allows us to store our data in tabular, multi-dimensional objects with familiar features like rows, columns, and headers. You will now import that pandas package by using the command below. This allows us to call funcitons from pandas with pd instead of pandas.

In [1]:
import pandas as pd

# Using the pd.read_csv() function

##### pd.read_csv reads the tabular data from a Comma Seperated Values (csv) file into a dataframe object we'll define as John. To create our dataframe object we'll type in exactly what is written below.

In [2]:
John=pd.read_csv("CountyHealthData_2014-2015 (1).csv")

# Pulling Out The Data

##### To select the certain columns we want we list the names of the columns inside brackets (John[["State", "Year", "County"]]). To select the certain rows we want we put the numbers of the rows we want in brackets (John[751:1068]). Look below to see exactly how it is done.

In [3]:
John[["State", "Year", "County", "Premature death", "Adult smoking", "Adult obesity", "Food environment index", "Excessive drinking", "Teen births", "Primary care physicians"]][751:1068]

,State,Year,County,Premature death,Adult smoking,Adult obesity,Food environment index,Excessive drinking,Teen births,Primary care physicians
751,GA,1/1/2015,Appling County,11232.0,0.278,0.347,6.800,NaN,91.1,49.0
752,GA,1/1/2014,Atkinson County,10394.0,NaN,0.308,5.773,NaN,91.6,NaN
753,GA,1/1/2015,Atkinson County,11413.0,NaN,0.342,5.500,NaN,90.2,NaN
754,GA,1/1/2014,Bacon County,10792.0,NaN,0.308,7.459,NaN,91.6,45.0
755,GA,1/1/2015,Bacon County,10997.0,NaN,0.318,7.300,NaN,93.3,45.0
...,...,...,...,...,...,...,...,...,...,...
1063,GA,1/1/2015,Wilkes County,10365.0,NaN,0.337,4.600,NaN,49.2,60.0
1064,GA,1/1/2014,Wilkinson County,10247.0,NaN,0.321,6.446,NaN,61.5,11.0
1065,GA,1/1/2015,Wilkinson County,10280.0,NaN,0.340,6.200,NaN,53.7,10.0
1066,GA,1/1/2014,Worth County,7936.0,0.258,0.316,6.883,NaN,48.4,23.0
1067,GA,1/1/2015,Worth County,7292.0,0.258,0.342,6.600,NaN,49.2,23.0

# Saving Subset

##### In order to save the subset of data you will type in what is below, but instead of Gahealthdata you will type in whatver you want to name it.

In [6]:
Gahealthdata_subset=John[John["State"]=="GA"].copy()

##### Now if you ever want to use your subset you just type in the name of it and _subset as you can see below.

In [7]:
Gahealthdata_subset

,State,Region,Division,County,FIPS,GEOID,SMS Region,Year,Premature death,Poor or fair health,...,Drug poisoning deaths,Uninsured adults,Uninsured children,Health care costs,Could not see doctor due to cost,Other primary care providers,Median household income,Children eligible for free lunch,Homicide rate,Inadequate social support
750,GA,South,South Atlantic,Appling County,13001,13001,Region 15,1/1/2014,11116.0,0.239,...,NaN,0.305,0.128,9763.0,0.242,71.0,35757,0.588,9.54,NaN
751,GA,South,South Atlantic,Appling County,13001,13001,Region 15,1/1/2015,11232.0,0.239,...,8.66,0.302,0.104,10563.0,0.242,76.0,36915,0.601,12.60,NaN
752,GA,South,South Atlantic,Atkinson County,13003,13003,Region 24,1/1/2014,10394.0,0.296,...,NaN,0.416,0.183,10290.0,NaN,12.0,28693,0.674,NaN,NaN
753,GA,South,South Atlantic,Atkinson County,13003,13003,Region 24,1/1/2015,11413.0,0.296,...,NaN,0.383,0.141,10454.0,NaN,12.0,30883,0.743,NaN,NaN
754,GA,South,South Atlantic,Bacon County,13005,13005,Region 1,1/1/2014,10792.0,0.132,...,NaN,0.328,0.125,12040.0,NaN,36.0,32460,0.529,NaN,0.153
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1063,GA,South,South Atlantic,Wilkes County,13317,13317,Insuff Data,1/1/2015,10365.0,NaN,...,NaN,0.250,0.078,10019.0,0.153,10.0,33662,0.663,NaN,NaN
1064,GA,South,South Atlantic,Wilkinson County,13319,13319,Region 24,1/1/2014,10247.0,0.230,...,NaN,0.245,0.104,9525.0,NaN,42.0,36219,0.746,NaN,NaN
1065,GA,South,South Atlantic,Wilkinson County,13319,13319,Region 24,1/1/2015,10280.0,0.230,...,NaN,0.238,0.089,10054.0,NaN,32.0,35745,0.763,NaN,NaN
1066,GA,South,South Atlantic,Worth County,13321,13321,Region 24,1/1/2014,7936.0,0.349,...,NaN,0.285,0.095,9232.0,0.288,28.0,35815,0.616,8.54,NaN
1067,GA,South,South Atlantic,Worth County,13321,13321,Region 24,1/1/2015,7292.0,0.349,...,NaN,0.291,0.090,9979.0,0.288,28.0,36616,0.655,9.30,NaN

# Exporting New Subset

##### Now that we are done creating our subset we can export it as a .csv file in our working directory. To do this we type in exactly what is written below, but instead of Gahealthdata type in what you named the subset.

In [8]:
Gahealthdata_subset.to_csv("Gahealthdata.csv",index=False)